use ts_rs::TS;

use crate::auth::microsoft::{DeviceCodeResponse, MicrosoftAuthResult};
use crate::auth::offline::OfflineAuthResult;
use crate::auth::token_store::StoredAccount;
use crate::auth::yggdrasil::{YggdrasilAuthResult, YggdrasilProfile};
use crate::collections::CollectionItem;
use crate::commands::optimization::{OptimizationPreset, PresetMod};
use crate::commands::server::ServerStatusInfo;
use crate::config::{AppConfig, SecurityConfig};
use crate::content::{InstallRecord, UpdateInfo};
use crate::crash_parser::{CrashDiagnosis, CrashFinding, CrashInfo};
use crate::instance::manager::GameInstance;
use crate::launch::state::LaunchState;
use crate::modrinth::{
    ModDependency, ModFile, ModGalleryImage, ModHashes, ModLicense, ModProjectFull, ModResult,
    ModVersion,
};
use crate::version::manifest::{LatestVersions, VersionEntry, VersionManifest};

const OUTPUT_DIR: &str = "../generated";

pub fn export_all_types() -> Result<(), Box<dyn std::error::Error>> {
    let out = std::path::Path::new(OUTPUT_DIR);
    std::fs::create_dir_all(out)?;

    let mut all_decls: Vec<String> = Vec::new();

    macro_rules! export_type {
        ($ty:ty) => {
            let decl = <$ty>::decl();
            all_decls.push(decl);
        };
    }

    export_type!(GameInstance);
    export_type!(AppConfig);
    export_type!(SecurityConfig);
    export_type!(MicrosoftAuthResult);
    export_type!(DeviceCodeResponse);
    export_type!(YggdrasilAuthResult);
    export_type!(YggdrasilProfile);
    export_type!(StoredAccount);
    export_type!(OfflineAuthResult);
    export_type!(LaunchState);
    export_type!(CollectionItem);
    export_type!(InstallRecord);
    export_type!(UpdateInfo);
    export_type!(CrashInfo);
    export_type!(CrashFinding);
    export_type!(CrashDiagnosis);
    export_type!(ServerStatusInfo);
    export_type!(OptimizationPreset);
    export_type!(PresetMod);
    export_type!(ModResult);
    export_type!(ModProjectFull);
    export_type!(ModGalleryImage);
    export_type!(ModLicense);
    export_type!(ModVersion);
    export_type!(ModFile);
    export_type!(ModHashes);
    export_type!(ModDependency);
    export_type!(VersionManifest);
    export_type!(LatestVersions);
    export_type!(VersionEntry);

    let mut output = String::new();
    output.push_str("// Auto-generated by BonNext types_export.rs — DO NOT EDIT\n");
    output.push_str("// Run: cargo test --lib types_export -- --nocapture\n\n");

    let mut seen = std::collections::HashSet::new();
    for decl in all_decls {
        let trimmed = decl.trim();
        if !trimmed.is_empty() && seen.insert(trimmed.to_string()) {
            output.push_str(trimmed);
            output.push_str("\n\n");
        }
    }

    let dest = out.join("types.ts");
    std::fs::write(&dest, output)?;
    println!("Types exported to {}", dest.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_types() {
        if let Err(e) = export_all_types() {
            eprintln!("Type export failed: {}", e);
            panic!("Type export failed");
        }
    }
}
